version: "3"
services:
  mongodb:
    image: mongo:4.2.6
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    env_file:
      - .env
    command: mongod --port ${MONGO_PORT}

  crawler:
    build: ./crawler
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./image_db:/usr/src/app/image_db

  face:
    build: ./face
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - "${FACE_PORT}:${FACE_PORT}"

  omg-back:
    build: ./omg-back
    depends_on:
      - mongodb
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    volumes:
      - ./image_db:/usr/src/app/image_db
    env_file:
      - .env
