version: "3"
services:
    ohmygirl:
        build: ./ohmygirl
        depends_on:
            - mongodb
        ports:
            - "3000"
        volumes: 
            - ./image_db:/usr/src/app/image_db
        env_file: 
            - .env

    mongodb:
        image: mongo:4.2.6
        volumes: 
            - ./mongodb/data/db:/data/db
        ports:
            - "27017:27017"
        
    crawler:
        build: ./crawler
        depends_on:
            - mongodb
        volumes: 
            - ./image_crawl:/usr/src/app/image_crawl

    face:
        build: ./face
        depends_on:
            - mongodb
        volumes: 
            - ./image_crawl:/usr/src/app/image_crawl
            - ./image_db:/usr/src/app/image_db

    omg-back:
        build: ./omg-back
        depends_on: 
            - mongodb
        ports:                                                                                                                                                                                                                                                                                                                                                                                                  
            - "4000"
        volumes:
            - -./image_db:/usr/src/app/image_db
        env_file: 
            - .env

networks:
    reverse-proxy_default:
        external: true
            
