version: "3"
services:
    ohmygirl:
        build: ./ohmygirl
        depends_on:
            - mongodb
        expose:
            - "3000"
        volumes: 
            - ./image_db:/usr/src/app/image_db
        env_file: 
            - .env

    mongodb:
        image: mongo:4.2.6
        volumes: 
            - ./mongodb/data/db:/data/db
        ports:
            - "27019:27019"
        env_file:
            - .env
        command: mongod --port 27019
        
    crawler:
        build: ./crawler
        depends_on:
            - mongodb
        env_file:
            - .env
        volumes: 
            - ./image_crawl:/usr/src/app/image_crawl

    face:
        build: ./face
        depends_on:
            - mongodb
        env_file:
            - .env
        volumes: 
            - ./image_crawl:/usr/src/app/image_crawl
            - ./image_db:/usr/src/app/image_db

    omg-back:
        build: ./omg-back
        depends_on: 
            - mongodb 
        ports:                                                                                                                                                                                                                                                                                                                                                                                                  
            - "3000"
        volumes:
            - ./image_db:/usr/src/app/image_db
        env_file: 
            - .env
           
