# Generated by Django 4.2.5 on 2023-09-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('training_status', models.CharField(choices=[('queue', 'Queue'), ('training', 'Training'), ('error', 'Error'), ('created', 'Created')], default='queue', max_length=50)),
                ('algorithm', models.CharField(choices=[('ball_tree', 'Ball Tree'), ('kd_tree', 'Kd Tree'), ('brute', 'Brute')], default='ball_tree', max_length=50)),
            ],
            options={
                'db_table': 'classifier',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=255)),
                ('thumbnail_url', models.CharField(max_length=255)),
                ('annotation', models.CharField(choices=[('arin', 'Arin'), ('mimi', 'Mimi'), ('yooa', 'Yooa'), ('yubin', 'Yubin'), ('hyojung', 'Hyojung'), ('seunghee', 'Seunghee'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('test_images', models.ManyToManyField(to='api.image')),
            ],
            options={
                'db_table': 'test_set',
            },
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested_at', models.DateTimeField(null=True)),
                ('test_status', models.CharField(choices=[('queue', 'Queue'), ('testing', 'Testing'), ('error', 'Error'), ('finish', 'Finish')], default='queue', max_length=50)),
                ('answer_rate', models.FloatField(null=True)),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classifier')),
                ('test_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testset')),
            ],
            options={
                'db_table': 'test_record',
            },
        ),
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_member', models.CharField(choices=[('arin', 'Arin'), ('mimi', 'Mimi'), ('yooa', 'Yooa'), ('yubin', 'Yubin'), ('hyojung', 'Hyojung'), ('seunghee', 'Seunghee'), ('unknown', 'Unknown')], max_length=50)),
                ('result_member', models.CharField(choices=[('arin', 'Arin'), ('mimi', 'Mimi'), ('yooa', 'Yooa'), ('yubin', 'Yubin'), ('hyojung', 'Hyojung'), ('seunghee', 'Seunghee'), ('unknown', 'Unknown')], max_length=50)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
                ('test_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testrecord')),
            ],
            options={
                'db_table': 'image_result',
            },
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['annotation'], name='image_annotat_00d83a_idx'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='training_images',
            field=models.ManyToManyField(to='api.image'),
        ),
        migrations.AddIndex(
            model_name='imageresult',
            index=models.Index(fields=['test_record'], name='image_resul_test_re_fb1b98_idx'),
        ),
    ]
