# Generated by Django 4.2.5 on 2023-09-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('thumbnail_url', models.CharField(max_length=255)),
                ('annotation', models.CharField(default='unknown', max_length=50)),
            ],
        ),
    ]
