# Generated by Django 4.2.5 on 2023-09-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
