# Generated by Django 4.2.5 on 2023-09-20 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['annotation'], name='api_image_annotat_cb6e17_idx'),
        ),
    ]
