# Generated by Django 4.2.5 on 2023-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='algorithm',
            field=models.CharField(choices=[('ball_tree', 'Ball Tree'), ('kd_tree', 'Kd Tree'), ('brute', 'Brute')], default='ball_tree', max_length=50),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='answer_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='trainging_status',
            field=models.CharField(choices=[('queue', 'Queue'), ('training', 'Training'), ('error', 'Error'), ('created', 'Created')], default='queue', max_length=50),
        ),
    ]
