# Generated by Django 4.2.5 on 2023-09-24 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_image_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('test_status', models.CharField(choices=[('queue', 'Queue'), ('error', 'Error'), ('testing', 'Testing'), ('finish', 'Finish')], default='queue', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='image',
            name='annotation',
            field=models.CharField(choices=[('arin', 'Arin'), ('mimi', 'Mimi'), ('yooa', 'Yooa'), ('yubin', 'Yubin'), ('hyojung', 'Hyojung'), ('seunghee', 'Seunghee'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
        migrations.CreateModel(
            name='TestImageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_member', models.CharField(choices=[('arin', 'Arin'), ('mimi', 'Mimi'), ('yooa', 'Yooa'), ('yubin', 'Yubin'), ('hyojung', 'Hyojung'), ('seunghee', 'Seunghee'), ('unknown', 'Unknown')], max_length=50)),
                ('result_member', models.CharField(choices=[('arin', 'Arin'), ('mimi', 'Mimi'), ('yooa', 'Yooa'), ('yubin', 'Yubin'), ('hyojung', 'Hyojung'), ('seunghee', 'Seunghee'), ('unknown', 'Unknown')], max_length=50)),
                ('test_result', models.CharField(choices=[('wait', 'Wait'), ('success', 'Success'), ('fail', 'Fail')], default='wait', max_length=50)),
                ('test_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
                ('test_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testset')),
            ],
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('trainging_status', models.CharField(max_length=50)),
                ('training_images', models.ManyToManyField(to='api.image')),
            ],
        ),
    ]
