# Generated by Django 4.2.5 on 2023-09-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testset_rename_image_url_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimageresult',
            old_name='test_set',
            new_name='test_record',
        ),
        migrations.RemoveField(
            model_name='testimageresult',
            name='test_image',
        ),
        migrations.RemoveField(
            model_name='testset',
            name='test_status',
        ),
        migrations.AddField(
            model_name='testset',
            name='test_images',
            field=models.ManyToManyField(to='api.image'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='trainging_status',
            field=models.CharField(default='queue', max_length=50),
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested_at', models.DateTimeField(null=True)),
                ('test_status', models.CharField(choices=[('queue', 'Queue'), ('error', 'Error'), ('testing', 'Testing'), ('finish', 'Finish')], default='queue', max_length=50)),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classifier')),
                ('test_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testset')),
            ],
        ),
    ]
