# Generated by Django 4.2.5 on 2023-09-24 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_test_set_testimageresult_test_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimageresult',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
            preserve_default=False,
        ),
    ]
