# Generated by Django 4.2.5 on 2023-09-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_testimageresult_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimageresult',
            name='test_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testrecord'),
        ),
    ]
