# Generated by Django 2.1 on 2019-10-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='hashtags',
            field=models.ManyToManyField(to='photo.Hashtag'),
        ),
    ]
